#Please fill the below form
name=("Sreenath Gupta")
print("Hello Mr. ",name,"Welcome to the world of Data Science. How are you doing today.")
name=input("Please type your full name in Block Letters: ")
martial_status=input("Are you Married or Single: ")
Gender=input("Male or Female: ")
Nationality=input("Resident_of_India : Yes/No: ")
experience=input("Years of experience in Data Science: ")
Xcompany=input("Details of previous company 1: ")
Xcompany=input("Details of previous company 2: ")
Xcompany=input("Details of previous company 3: ")
ctc=input("CTC: ")
Ectc=input("Expected CTC: ")
salary=input("Take home salary: ")
Notice_period=input("Notice Period: ")
print("Thank you Mr.",name,"For your patience in filling the form")
